BEGIN TRANSACTION;
CREATE TABLE `user` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL DEFAULT 'user_name'
);
CREATE TABLE `deck` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT,
	`user_id`	INTEGER NOT NULL
);
CREATE TABLE "card" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`deck_id`	INTEGER NOT NULL,
	`position`	INTEGER DEFAULT 0
);
COMMIT;
