BEGIN TRANSACTION;
CREATE TABLE `Users` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL DEFAULT 'user_name'
);
CREATE TABLE `Decks` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT,
	`user_id`	INTEGER NOT NULL
);
CREATE TABLE "Cards" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`deck_id`	INTEGER NOT NULL,
	'random_id' INTEGER NOT NULL,
	`position`	INTEGER DEFAULT 0
);
COMMIT;
